### ISSUE TITLE
not detecting motercycle wrong way

### ISSUE THREAD

**Issue by pushpesh95** [zillur-av/wrong-way-vehicle-detection#1]
please at least tell or add the code also for motorcycle wrong way detection. as in vehicle(car and motorbike both come) plz help in regarding this.

**Comment by zillur01** [comment]
In that case, instead of using my trained model, you can use a pre-trained one. Two ways it can be done:

1. Run the command ``` python detect_wrong.py --source overpass.mp4```. It will download a pre-trained model and use that automatically. Before running that command, edit line 182 in [```detect_wrong.py```](https://github.com/zillur-av/wrong-way-vehicle-detection/blob/main/yolov5/detect_wrong.py).
``` if ((ROI_MIN <= box_center <= ROI_MAX) and (int(cls)==1 or int(cls)==2)):``` to ```  if ((ROI_MIN <= box_center <= ROI_MAX) and (int(cls)==2 or int(cls)==3 or int(cls)==5 or int(cls)==7)):```

2. Run the command ``` python detect_wrong.py --source overpass.mp4 --classes 2,3,5,7```. Before running that command, edit line 182 in [```detect_wrong.py```](https://github.com/zillur-av/wrong-way-vehicle-detection/blob/main/yolov5/detect_wrong.py).
``` if ((ROI_MIN <= box_center <= ROI_MAX) and (int(cls)==1 or int(cls)==2)):``` to ```  if (ROI_MIN <= box_center <= ROI_MAX):```
